/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.List;
import java.util.ArrayList;

public class App {
    public static <T> List<T> zip(List<T> list1, List<T> list2){
        List<T> result = new ArrayList<>();

        int size = 0;
        if (list1.size() != 0 && list2.size() != 0){
            if (list1.size() > list2.size()){
            size = list2.size();
        } else{
            size = list1.size();
            }
        }
        

        for (int i = 0; i < size; i++) {
            if (i < list1.size()) {
                result.add(list1.get(i));
            }
            if (i < list2.size()) {
                result.add(list2.get(i));
            }
        }
        
        return result;
    }
    
    public static void main(String[] args) {
        List<Integer> nums1 = List.of(1, 3, 5, 7);
          List<Integer> nums2 = List.of(2, 4, 6, 8);
          List<Integer> mergedNumbers = zip(nums1, nums2);
          System.out.println(mergedNumbers); // [1, 2, 3, 4, 5, 6, 7, 8]

          List<String> colors1 = List.of("Red", "Green", "Blue");
          List<String> colors2 = List.of("White", "Black", "Orange", "Pink", "Fuschia");
          List<String> mergedWords = zip(colors1, colors2);
          System.out.println(mergedWords); // ["Red", "White", "Green", "Black", "Blue", "Orange", "Pink", "Fuschia"]
    }
}
